policies:
product_name:
product_version:
ignored_patterns:
  - '*/environment.yml'
  - '*/main'
  - '*.o'
  - '.miniforge/*'
  - '*/default.nix'
  - '*/conda_lock_to_about.py'
  - '*.github/*'
scan_max_file_size:
attribution_template:
ignored_vulnerabilities:
ignored_dependency_scopes: